// Liste complète des prêteurs d'argent du Québec
// Source: OPC (Office de la protection du consommateur)
// Total: 548 noms
// Généré automatiquement le 2025-12-15

export const PRETEURS_CONNUS = [
    '10013137 canada inc.',
    '10336874 canada inc.',
    '10540803 canada inc.',
    '12072521 canada inc.',
    '12753901 canada inc.',
    '13440222 canada inc.',
    '14320956 canada inc.',
    '14333527 canada inc.',
    '147402 canada inc.',
    '15630070 canada inc.',
    '15771447 canada inc.',
    '16086497 canada inc.',
    '16104274 canada inc.',
    '17121504 canada inc.',
    '2552-4018 quebec inc.',
    '2732-2304 québec inc.',
    '3717 plus multiservices inc.',
    '3iemechance.ca',
    '4141 globe capital corporation',
    '500 préférentiel',
    '6651038 canada incorporated',
    '8341869 canada inc.',
    '9131-2561 québec inc.',
    '9151-7854 québec inc.',
    '9153-7639 québec inc.',
    '9154-7323 québec inc.',
    '9155-4188 québec inc.',
    '9160-4181 québec inc.',
    '9250-6468 québec inc.',
    '9265-2791 québec inc.',
    '9281-7378 québec inc.',
    '9287-6408 québec inc.',
    '9292-7839 québec inc.',
    '9296-7660 québec inc.',
    '9321-3924 québec inc.',
    '9331-6255 québec inc.',
    '9342-1659 québec inc.',
    '9344-6326 québec inc.',
    '9350-3142 québec inc.',
    '9356-2015 québec inc.',
    '9358-5677 québec inc.',
    '9369-3521 québec inc.',
    '9370-0250 québec inc.',
    '9374-0207 québec inc.',
    '9375-9652 québec inc.',
    '9376-5683 québec inc.',
    '9380-6545 québec inc.',
    '9381-9167 québec inc.',
    '9387-4832 québec inc.',
    '9389-1562 québec inc.',
    '9389-2263 québec inc.',
    '9391-0040 québec inc.',
    '9394-5806 québec inc.',
    '9396-6539 québec inc.',
    '9397-3741 québec inc.',
    '9404-5283 québec inc.',
    '9413-9029 québec inc.',
    '9414-8327 québec inc.',
    '9430-6032 québec inc.',
    '9431-8375 québec inc.',
    '9439-3428 québec inc.',
    '9443-1905 québec inc.',
    '9444-1961 québec inc.',
    '9445-2976 québec inc.',
    '9445-3933 québec inc.',
    '9447-2420 québec inc.',
    '9448-0530 québec inc.',
    '9448-4524 québec inc.',
    '9449-8110 québec inc.',
    '9451-8107 québec inc.',
    '9456-3475 québec inc.',
    '9458-0842 québec inc.',
    '9459-5576 québec inc.',
    '9459-9644 québec inc.',
    '9461-4682 québec inc.',
    '9461-5333 québec inc.',
    '9466-4646 québec inc.',
    '9470-0077 québec inc.',
    '9472-7732 québec inc.',
    '9472-7740 québec inc.',
    '9472-9928 québec inc.',
    '9473-2229 québec inc.',
    '9474-0636 québec inc.',
    '9475-6152 québec inc.',
    '9476-5138 québec inc.',
    '9476-6391 québec inc.',
    '9480-6874 québec inc.',
    '9483-9586 québec inc.',
    '9485-6903 québec inc.',
    '9486-0319 québec inc.',
    '9487-2942 québec inc.',
    '9487-6430 québec inc.',
    '9488-1828 québec inc.',
    '9488-9755 québec inc.',
    '9490-3804 québec inc.',
    '9492-8322 québec inc.',
    '9492-8454 québec inc.',
    '9492-8462 québec inc.',
    '9493-1144 québec inc.',
    '9495-9350 québec inc.',
    '9496-3915 québec inc.',
    '9497-1827 québec inc.',
    '9499-8002 québec inc.',
    '9500-0238 québec inc.',
    '9502-1713 québec inc.',
    '9502-4725 québec inc.',
    '9503-3700 québec inc.',
    '9503-7628 québec inc.',
    '9504-5324 québec inc.',
    '9504-9854 québec inc.',
    '9505-9440 québec inc.',
    '9506-3079 québec inc.',
    '9506-9704 québec inc.',
    '9507-1791 québec inc.',
    '9508-9215 québec inc.',
    '9509-3951 québec inc.',
    '9509-4637 québec inc.',
    '9509-8638 québec inc.',
    '9510-7249 québec inc.',
    '9516-6278 québec inc.',
    '9517-4710 québec inc.',
    '9520-0275 québec inc.',
    '9520-9185 québec inc.',
    '9521-0530 québec inc.',
    '9521-2114 québec inc.',
    '9521-5117 québec inc.',
    '9522-2881 québec inc.',
    '9523-5883 québec inc.',
    '9524-1881 québec inc.',
    '9525-2987 québec inc.',
    '9526-1202 québec inc.',
    '9526-8769 québec inc.',
    '9527-1953 québec inc.',
    '9527-9808 québec inc.',
    '9537-7008 québec inc.',
    '9543-2860 québec inc.',
    '9548-2634 québec inc.',
    '9548-7385 québec inc.',
    '955prêt.ca',
    'a1 argent',
    'accès finances plus',
    'achat en ligne',
    'advance 24',
    'affirm canada - financial services company',
    'affirm canada - société de services financiers',
    'affirm canada holdings ltd.',
    'agence de recouvrement fina',
    'aide prêts inc.',
    'aideimmo inc.',
    'aim finance',
    'alexandre diderot',
    'aleza inc.',
    'aller cinq cent',
    'alterfina',
    'apx inc.',
    'aqua services',
    'arbre à devises inc.',
    'arfc finance',
    'argent comptant kobca$h inc.',
    'argent express plus',
    'argent magik',
    'argent maintenant',
    'argent rapide 911',
    'argent sécure',
    'asc finances',
    'aubaine multi-comptant',
    'auto durocher',
    'automobile vision',
    'autonum presto locations inc.',
    'banco',
    'beautifi lending inc.',
    'belabri inc.',
    'besoinargentenligne.com',
    'boddi design',
    'boîte comptant',
    'boîte de prêt',
    'c2g finance',
    'can finance',
    'can finance option',
    'can finance plus',
    'can finance solution',
    'canada finance plus',
    'canada finance solution',
    'canadian asset based lending enterprise (cable) inc.',
    'canadian life settlements',
    'capital garanti',
    'capital jayco inc.',
    'capital lendcare',
    'capital plus',
    'capital transit inc.',
    'capitale card',
    'capitale ryan inc.',
    'carl service de dignité',
    'carrefour automobiles rive-nord',
    'carte capitale',
    'cash cowboy 500',
    'cash québec',
    'cashelle',
    'cdn credit inc.',
    'centre de collision rive-nord',
    'chery milot',
    'chomedey hyundai',
    'cliffton leasing inc.',
    'concept financier eurêka inc.',
    'consultationsimple',
    'corporation crédit médical',
    'courtier ipawn mm',
    'credit medical',
    'credit station inc.',
    'credit yamaska',
    'creditmatik',
    'crédit cdi',
    'crédit courtage',
    'crédit dépanneur',
    'crédit direct rapide inc.',
    'crédit excellence a.t.g.',
    'crédit médical',
    'crédit optimum',
    'crédit privilège',
    'crédit toledo inc.',
    'crédit unique',
    'créditfina',
    'crédika',
    'currencies tree inc.',
    'deltafina',
    'demande de prêt',
    'depotrapide.ca',
    'diamond financial service',
    'dion services financiers',
    'donovan financial services inc.',
    'east mountain finance inc.',
    'easyconsulting',
    'easyfinancial services inc.',
    'easyfinancière (tm)',
    'eden park mc',
    'edenpark mc',
    'électro-loisirs stjb inc.',
    'emprunt facile',
    'empruntrapide.com',
    'entrepôt auto durocher',
    'est ouest crédit',
    'evasion sport inc.',
    'express payday loan',
    'fairstone financial inc.',
    'fairstone financière',
    'fairstone financière inc.',
    'fastcash 911',
    'fastforloan',
    'fep enr.',
    'fig financial inc.',
    'finacapitale',
    'financement 116 inc.',
    'financement à ma façon inc.',
    'financement auto 60 minutes',
    'financement capital bl inc.',
    'financement dp inc.',
    'financement eden park',
    'financement edenpark',
    'financement et crédit rive-sud inc.',
    'financement eurëka',
    'financement express',
    'financement fidèle',
    'financement gagliano',
    'financement green river',
    'financement gsp',
    'financement marfil inc.',
    'financement ncr',
    'financement prefera',
    'financement sourire inc.',
    'financement unik',
    'finart capital',
    'finance 24',
    'finance arfc',
    'finance east mountain inc.',
    'finance gagliano',
    'finance jd euroway inc.',
    'finance rentugo',
    'financeit canada inc.',
    'financier de grande hauteur',
    'financier huard',
    'financière de grandes hauteurs',
    'financière dig',
    'financière finstar inc.',
    'financière geneva',
    'financière lendful',
    'financière mcg',
    'financière mbo',
    'financière northlake',
    'financière sprint',
    'financière trinité',
    'financière tritan',
    'financière twist',
    'first stop loans',
    'flash loan',
    'flash sélection',
    'flex pay',
    'flexiti (mc)',
    'flexiti financial',
    'flexiti financial inc.',
    'flexiti financière',
    'fond-action santé communautaire bénise normil (fascbn)',
    'fondation lise watier',
    'fonds populaire du millénaire',
    'fs prêt',
    'gabriel gary',
    'gagliano finance',
    'garage p. venne inc.',
    'gary gabriel marketing',
    'gervais auto inc.',
    'gestion & investissements cali inc.',
    'gestion 920',
    'gestion asc',
    'gestion bgorry inc.',
    'gestion conseil prp inc.',
    'gestion crl',
    'gestion duforge inc.',
    'gestion financière mpc',
    'gestion financière r.r inc.',
    'gestion flf',
    'gestion jette lemay inc.',
    'gestion jkr',
    'gestion multi crédit',
    'gestion multi-finance inc.',
    'gestion odc',
    'gestion olla inc.',
    'gestion ppa',
    'gestion premium',
    'gestion spcq',
    'gestion vinmax inc.',
    'global finance canada',
    'global ir communications inc.',
    'go crédit',
    'go prêt',
    'goeasy®',
    'gofivehundred',
    'granby toyota',
    'groupe 369 cl',
    'groupe accès rapide inc.',
    'groupe arbre d\'argent',
    'groupe b. won inc.',
    'groupe buck',
    'groupe c2g inc.',
    'groupe de gestion heyday',
    'groupe dmf (2023) inc.',
    'groupe en demande',
    'groupe finexa',
    'groupe fiodih inc.',
    'groupe financier stell-art',
    'groupe gagnon inc.',
    'groupe immobilier trinité inc.',
    'groupe insta 500 inc.',
    'groupe investisseurs ml & associés inc.',
    'groupe liberté inc.',
    'groupe psp xpress',
    'groupe scf',
    'groupe simple500 inc.',
    'groupe speedy inc.',
    'groupe stocan 2011 inc.',
    'groupe venne',
    'group simple500 inc.',
    'gsp express inc.',
    'guru capital',
    'h. grégoire saguenay',
    'h.t. tremblay inc.',
    'haute liberté finances inc.',
    'hc finances',
    'héros du jour de paie',
    'héros payant',
    'high liberty finances inc.',
    'high rise financial',
    'ia auto finance inc.',
    'ia financement auto inc.',
    'iceberg finance inc.',
    'if xpress md',
    'ifinance canada inc.',
    'im finances',
    'immobilier & hypothèque un toit',
    'impot etoile enr',
    'infiniti',
    'infiniti financial services',
    'insta prêt 3d inc.',
    'insta-cheques',
    'instant auto crédit',
    'instant loans cash',
    'instant prêt',
    'investissement inferno inc.',
    'investissement or-immo',
    'investissement spartan inc.',
    'j.p. financial',
    'j.p. financial services',
    'johnson health technologies canada commercial inc.',
    'k3n finance',
    'kia québec',
    'kia ste-foy',
    'kia val-bélair',
    'klarna canada limited',
    'kps financial services inc.',
    'krédit prêt inc.',
    'la capitale civil service insurer inc.',
    'la capitale mutuelle de l\'administration publique',
    'la financière prêtbec ltée',
    'la financière transcapitale inc.',
    'le groupe stocan 2011 inc.',
    'le moulin microcrédits',
    'lendcare capital inc.',
    'lendful financial inc.',
    'lendorado services inc.',
    'lendora',
    'les entreprises lachance inc.',
    'les entreprises ro-jo enr.',
    'les investissements jean lortie inc.',
    'les investissements senneville inc.',
    'les placements gasmic inc.',
    'les placements j. campeau inc',
    'les placements jc.d.a.',
    'les placements jeanclo inc.',
    'les placements msn',
    'les services financiers plan b',
    'les services lendorado',
    'les services rapidoloan',
    'les solutions prêteurs inc.',
    'les systèmes d\'eau eagle inc.',
    'les technologies johnson health canada commercial inc.',
    'libe prêt privé inc.',
    'lion capital',
    'lm crédit',
    'lm credit inc.',
    'loan click',
    'loans 500',
    'location accès crédit inc.',
    'location cliffton inc.',
    'location elite inc.',
    'location mirage',
    'location richelieu',
    'loonie financial',
    'magnat location et financement',
    'manufacture de bijoux unique inc.',
    'marketing quickneasy',
    'mat\'prêter inc.',
    'mdg',
    'mdg finance',
    'mdg financial',
    'mdg financial inc.',
    'mdg financier',
    'micro-crédit fomalu inc.',
    'micro-prêt',
    'microsprets.ca',
    'miniargent',
    'minicash',
    'mon argent comptant',
    'mon temps service financier ltée',
    'mon temps solde service financier inc.',
    'money mart™',
    'money tree group',
    'montestrie autorama inc.',
    'mutuelle beneva',
    'my cash pay',
    'my way financing inc.',
    'mypayroll inc.',
    'mapaie',
    'national money mart company',
    'ncr finance',
    'ncr financial',
    'ncr financial services',
    'ncr financing',
    'ncr loans',
    'neo capital',
    'neo financial ®',
    'neo financial technologies inc.',
    'nic finance',
    'nissan canada finance',
    'nissan canada inc.',
    'northlake financial ulc',
    'novaargent',
    'novacash',
    'novilo',
    'novilo finance',
    'objectif finance',
    'occasion prilo',
    'occasion rive-nord',
    'occasion sans limite',
    'occasion ville de longueuil',
    'occasion ville de québec',
    'ouellet jean-yves',
    'oxbridge',
    'paf redressement et services comptables inc.',
    'paie flex',
    'paie par mois',
    'pay hero',
    'pay monthly',
    'paybright financial services',
    'payday hero',
    'peer capital corporation',
    'peer société de capital',
    'petitsprêts.ca',
    'pmc solutions',
    'prefera finance ltd.',
    'prempay corp.',
    'premium financière',
    'pret olympique',
    'pretécho',
    'pretheure',
    'pretxtra.ca',
    'pretxtra.com',
    'prets ncr',
    'pretsargent.com',
    'prime 500',
    'prilo occasion',
    'problemeargent.com',
    'prt financière',
    'prêt 24',
    'prêt accept',
    'prêt alternatif inc.',
    'prêt bonne vie',
    'prêt boutique',
    'prêt bsl inc.',
    'prêt capital',
    'prêt click',
    'prêt comptant',
    'prêt dépanneur',
    'prêt eclair',
    'prêt en ligne',
    'prêt étudiant',
    'prêt formula',
    'prêt hebdo inc.',
    'prêt instant',
    'prêt intelligent inc.',
    'prêt magique',
    'prêt monarque',
    'prêt mont-laurier',
    'prêt olympique',
    'prêt oopsy',
    'prêt pas prêt j\'y vais s.e.n.c.',
    'prêt premier arrêt',
    'prêt pour aider',
    'prêt qc',
    'prêt rapide',
    'prêt rapide 247',
    'prêt rapide mab',
    'prêt s.o.s. cash',
    'prêt sans crédit',
    'prêt solution',
    'prêt sécure',
    'prêt sur salaire express',
    'prêt urgent',
    'prêteur d\'argent milca',
    'prêtextra inc.',
    'prêtintelligent500',
    'prêtpersonnel.co',
    'prêts 500',
    'prêts apx',
    'prêts infinity inc.',
    'prêts instantanés cash',
    'prêts nano inc.',
    'prêts quicky',
    'prêts rapides charest holding',
    'prêts rapido',
    'prêt-atout',
    'prêt-à-tout',
    'puromobile',
    'puropaiement',
    'québec auto finance',
    'quickfund solution',
    'quickloans',
    'quickneasy marketing',
    'quicky loans',
    'rachat d\'assurance-vie canadien',
    'rapid credit mp inc.',
    'rapidoprêt',
    'rentugo finance inc.',
    'rh holding inc.',
    'roi rapide',
    'scooby',
    'sécuriprêt',
    'service de financement astral finance',
    'service financier diamant',
    'service rapide',
    'services au détail citi',
    'services au détail citifinancière',
    'services de crédit alternatif inc.',
    'services financement capital inc.',
    'services financiers 57',
    'services financiers agri-com ltée',
    'services financiers athena inc.',
    'services financiers dell canada',
    'services financiers dell canada limitée',
    'services financiers donovan inc.',
    'services financiers esnat (2000) inc.',
    'services financiers infiniti',
    'services financiers j.p.',
    'services financiers kps inc.',
    'services financiers ncr',
    'services financiers paybright',
    'services financiers saphir inc.',
    'scotiabank',
    'scotiabank auto loan',
    'scotiabank auto finance',
    'simplecr',
    'simplecredit',
    'smile financing inc.',
    'société en commandite kadek',
    'soin prêt',
    'solidex loans inc.',
    'solidex prêts inc.',
    'solution crédit finance',
    'solution de financement rapide',
    'solution flexco inc.',
    'solution pmc',
    'solutions alterfina',
    'solutions capitales inc.',
    'solutions comptant',
    'specialistedupret.com',
    'specialistemicropret.ca',
    'speedy king',
    'sphinx services financiers inc.',
    'spring financial inc.',
    'sprint financial',
    'ssq mutuelle',
    'stalk carolyn',
    'station crédit inc.',
    'strato capital',
    'subaru boisbriand',
    'subaru rive-nord',
    'système dash',
    'the lenders solutions inc.',
    'toledo credit inc.',
    'tritan financial',
    'unique jewellery manufacturing inc.',
    'uplift canada services ulc',
    'uplift ™',
    'vag finance',
    'venne ford',
    'verticalefinance inc.',
    'viacash inc.',
    'vision automobile',
    'vitopret',
    'voodoo',
    'windmill microlending',
    'zum rails',
    'zumrail',
    'émeraude financière',
    'énergir',
    'énergir l.p.',
    'équiprêt solution'
];
